plugin: aws_ec2
boto_profile: default
regions:
  - us-east-2
filters:    
    instance-state-name: running
    tag:Name: exetel_assignment
keyed_groups:
  - key: tags.Role
    separator: ""
compose:
  ansible_host: private_ip_address