---
- name: Install Nginx
  apt: name=nginx state=latest

- name: Start nginx service
  service:
      name: nginx
      state: started

- name: Enable nginx service
  service:
      name: nginx
      state: enabled