---
- name: Creates directory
  file:
    path: /home/ubuntu/aws-ec2-instance-id-app
    state: directory

- name: Aws Configure
  shell: |
    export AWS_ACCESS_KEY_ID=secrets.AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=secrets.AWS_SECRET_ACCESS_KEY

- name: Install npm 
  shell: |
    cd /home/ubuntu/aws-ec2-instance-id-app
    npm install aws-sdk
    npm init -y
    npm install express

- name: Copy application
  template:
    src: app.js
    dest: /home/ubuntu/aws-ec2-instance-id-app/app.js

- name: Start apllication
  shell: |
    cd /home/ubuntu/aws-ec2-instance-id-app
    node app.js



