---
- name: Creates directory For Apllication
  file:
    path: /home/ubuntu/aws-ec2-instance-id-app
    state: directory

- name: Install npm Dependencies
  shell: |
    cd /home/ubuntu/aws-ec2-instance-id-app
    npm install aws-sdk
    npm init -y
    npm install express

- name: Copy application
  template:
    src: app.js
    dest: /home/ubuntu/aws-ec2-instance-id-app/app.js

- name: Start apllication
  shell: |
    cd /home/ubuntu/aws-ec2-instance-id-app
    sudo kill -9 `sudo lsof -t -i:3000`
    nohup node app.js &



