---
- name: Delete Exixting Configurations 
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/sites-available/default

- name: Copy application
  template:
    src: node.j2
    dest: /etc/nginx/sites-available/default

- name: Restart nginx
  service:
      name: nginx
      state: restarted
