name: Ansible Playbook Deployment 

on:
  push:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible.yml'
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        playbook: ansible/playbook/nginx.yml 
        directory: ./
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        inventory: ${{ secrets.ansible_inventory }}
        options: |
          --extra-var ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}  SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
         