name: Ansible Playbook Deployment 

on:
  push:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible.yml'
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: perimission cange on ec2.py 
      run: |
        chmod -x ansible/inventory/ec2.py

    - name: Run ansible script
      shell: bash 
      run: |
        service ssh status
        cd ansible/playbook
        cat nginx.yml
        ansible-playbook  -i ../inventory nginx.yml
