name: Ansible Playbook Deployment 

on:
  push:
    paths:
      - 'ansible/**'
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Run ansible script
      shell: bash 
      run: |
        service ssh status
        cd ansible
        cat nginx.yml
        ansible-playbook  -i ansible/inventory nginx.yml
