name: Provision AWS lambda And API gateway
on:
  push:
    paths:
      - 'infrastructure/**'
    branches:
      - main
jobs:
  deploy:
    name: Infra Creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        run: |
          cd infrastructure/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
